{{ if eq .Values.genians_nac6_enable "yes" }}
{{ if eq .Values.genians_nac6_neo4j_enable "yes" }}

apiVersion: batch/v1
kind: Job
metadata:
  name: "neo4j-ztna-cleanup"
  labels:
    app: "neo4j-ztna-cleanup"
  annotations:
    "helm.sh/hook": "pre-delete"
    "helm.sh/hook-weight": "3"
spec:
  template:
    metadata:
      labels:
        app: "neo4j-ztna-cleanup"
    spec:
      serviceAccountName: "neo4j-ztna-cleanup"
      containers:
        - name: kubectl
          image: "docker.io/bitnami/kubectl:1.24"
          imagePullPolicy: "IfNotPresent"
          command: [ "/bin/sh" ]
          args:
            - -c
            - >-
              kubectl delete service -n default neo4j-ztna-lb --ignore-not-found=true &&
              kubectl wait --for=delete service -n default neo4j-ztna-lb
      restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "neo4j-ztna-cleanup"
  labels:
    app: neo4j-ztna
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "neo4j-ztna-cleanup"
  labels:
    app: neo4j-ztna
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "neo4j-ztna-cleanup"
  labels:
    app: neo4j-ztna
subjects:
  - kind: ServiceAccount
    name: "neo4j-ztna-cleanup"
roleRef:
  kind: Role
  name: "neo4j-ztna-cleanup"
  apiGroup: rbac.authorization.k8s.io

{{ end }}
{{ end }}
