{{ if eq .Values.genians_nac6_enable "yes" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-nac6-config
  labels:
    app: mysql-nac6
data:
  genians.cnf: |
    [mysqld]
    character-set-server = utf8mb4
    collation-server = utf8mb4_general_ci

    default-authentication-plugin = mysql_native_password
    log_bin_trust_function_creators = 1

    performance_schema = off
    explicit_defaults_for_timestamp = true

    max_connections = 4096
    max_allowed_packet = 16M
    key_buffer_size = 32M
    read_rnd_buffer_size = 2M
    join_buffer_size = 1M

    group_concat_max_len = 16384

    myisam_sort_buffer_size = 128M
    myisam_recover_options = DEFAULT

    ft_min_word_len = 2
    ft_stopword_file = 

    innodb_buffer_pool_size = 256M
    innodb_log_file_size = 32M
    innodb_flush_method = O_DIRECT
    innodb_flush_log_at_trx_commit = 2
    #innodb_force_recovery = 4

    thread_cache_size = 5

    tmp_table_size = 64M
    max_heap_table_size = 64M

    interactive_timeout = 1800
    wait_timeout = 1800

    sql_mode = "NO_ENGINE_SUBSTITUTION"

    slow_query_log = 1
    long-query-time = 2
    #log-queries-not-using-indexes
{{ if eq .Values.genians_certification_enable "yes" }}
    slow_query_log_file = /var/log/mysql/slowquery.log

    log-error = /var/log/mysql/error.log

    general_log = 1
    general_log_file = /var/log/mysql/general.log
{{ else }}
    #slow_query_log_file = /var/log/mysql/slowquery.log

    #log-error = /var/log/mysql/error.log

    general_log = 0
    #general_log_file = /var/log/mysql/general.log
{{ end }}
{{ end }}
