{{ if eq .Values.genians_nac6_neo4j_enable "yes" }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: "neo4j-ztna"
    helm.neo4j.com/neo4j.name: "neo4j-ztna"
    helm.neo4j.com/clustering: "true"
    helm.neo4j.com/instance: neo4j-ztna
  name: neo4j-ztna
  namespace: "default"
spec:
  serviceName: "neo4j-ztna"
  podManagementPolicy: "Parallel"
  replicas: {{ .Values.neo4j.replicas }}
  selector:
    matchLabels:
      app: "neo4j-ztna"
      helm.neo4j.com/instance: "neo4j-ztna"
  template:
    metadata:
      labels:
        app: "neo4j-ztna"
        helm.neo4j.com/neo4j.loadbalancer: "include"
        helm.neo4j.com/neo4j.name: "neo4j-ztna"
        helm.neo4j.com/clustering: "true"
        helm.neo4j.com/pod_category: "neo4j-instance"
        helm.neo4j.com/instance: "neo4j-ztna"
      annotations:
        "checksum/neo4j-ztna-config": {{ include (print $.Template.BasePath "/neo4j-ztna-configmap.yaml") . | sha256sum }}
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: role-backend
                  operator: In
                  values:
                  - "true"
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - "neo4j-ztna"
                topologyKey: "kubernetes.io/hostname"
      securityContext: 
        fsGroup: 7474
        fsGroupChangePolicy: Always
        runAsGroup: 7474
        runAsNonRoot: true
        runAsUser: 7474
      terminationGracePeriodSeconds: 3600
      containers:
        - name: "neo4j"
          image: "neo4j:{{- .Values.neo4j.version -}}"
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: "neo4j-ztna-env"
            - secretRef:
                name: "neo4j-ztna-pass"
          env:
            - name: HELM_NEO4J_VERSION
              value: {{ .Values.neo4j.version }}
            - name: HELM_CHART_VERSION
              value: {{ .Values.neo4j.version }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NEO4J_ADMIN
              value: "neo4j-ztna-admin.default.svc.cluster.local"
            - name: SERVICE_NEO4J_INTERNALS
              value: "neo4j-ztna-internals.default.svc.cluster.local"
            - name: SERVICE_NEO4J
              value: "neo4j-ztna.default.svc.cluster.local"
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
            - containerPort: 7473
              name: https
            - containerPort: 6362
              name: backup
          resources:
            requests: 
              cpu: "0.5"
              memory: 2Gi
            limits: 
              cpu: "0.5"
              memory: 2Gi
          securityContext:
              runAsGroup: 7474
              runAsNonRoot: true
              runAsUser: 7474
          volumeMounts:
            - mountPath: "/usr/share/neo4j/config/neo4j.conf"
              name: neo4j-conf
            - mountPath: "/usr/share/neo4j/config/server-logs.xml"
              name: neo4j-server-logs
            - mountPath: "/usr/share/neo4j/config/user-logs.xml"
              name: neo4j-user-logs
            - mountPath: "/usr/share/neo4j/config/"
              name: "apoc-conf"
            - mountPath: "/usr/share/neo4j/data"
              name: "neo4j-ztna-data"
              subPathExpr: "data"
            - mountPath: "/usr/share/neo4j/logs"
              name: "neo4j-ztna-data"
              subPathExpr: "logs"
          readinessProbe:
            tcpSocket:
              port: 7687
            failureThreshold: 20
            timeoutSeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 7687
            failureThreshold: 40
            timeoutSeconds: 10
            periodSeconds: 5
          startupProbe:
            tcpSocket:
              port: 7687
            failureThreshold: 1000
            periodSeconds: 5
      volumes:
        - name: neo4j-conf
          projected:
            defaultMode: 0440
            sources:
              - configMap:
                  name: "neo4j-ztna-default-config"
              - configMap:
                  name: "neo4j-ztna-user-config"
              - configMap:
                  name: "neo4j-ztna-k8s-config"
        - name: neo4j-server-logs
          configMap:
            name: "neo4j-ztna-server-logs-config"
        - name: neo4j-user-logs
          configMap:
            name: "neo4j-ztna-user-logs-config"
        - name: apoc-conf
          projected:
            defaultMode: 0440
            sources:
              - configMap:
                  name: "neo4j-ztna-apoc-config"
  volumeClaimTemplates: 
    - metadata:
        name: "neo4j-ztna-data"
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: "neo4j-ztna-lb"
  namespace: "default"
  labels:
    app: "neo4j-ztna"
    helm.neo4j.com/service: "neo4j"
    helm.neo4j.com/neo4j.name: "neo4j-ztna"
spec:
  {{- .Values.neo4j_ztna.service.spec | toYaml | nindent 4 }}
---
# ClusterIP service for bolt / http connections
apiVersion: v1
kind: Service
metadata:
  name: "neo4j-ztna"
  namespace: default
  labels:
    app: "neo4j-ztna"
    helm.neo4j.com/service: "default"
spec:
  publishNotReadyAddresses: false
  type: ClusterIP
  selector:
    app: "neo4j-ztna"
  ports:
    - protocol: TCP
      port: 7687
      targetPort: 7687
      name: tcp-bolt
    - protocol: TCP
      port: 7474
      targetPort: 7474
      name: tcp-http
    - protocol: TCP
      port: 7473
      targetPort: 7473
      name: tcp-https
---
# ClusterIP service for admin connections to Neo4j inside Kubernetes.
apiVersion: v1
kind: Service
metadata:
  name: "neo4j-ztna-admin"
  namespace: default
  labels:
    app: "neo4j-ztna"
    helm.neo4j.com/service: "admin"
    helm.neo4j.com/neo4j.name: "neo4j-ztna"
    helm.neo4j.com/instance: "neo4j-ztna"
spec:
  publishNotReadyAddresses: true
  type: "ClusterIP"
  selector:
    app: "neo4j-ztna"
    
  ports:
    - protocol: TCP
      port: 6362
      targetPort: 6362
      name: tcp-backup
    - protocol: TCP
      port: 7687
      targetPort: 7687
      name: tcp-bolt
    - protocol: TCP
      port: 7474
      targetPort: 7474
      name: tcp-http
    - protocol: TCP
      port: 7473
      targetPort: 7473
      name: tcp-https
---
{{ end }}