{{ if eq .Values.genians_nac6_neo4j_enable "yes" }}

{{- $password :=  randAlphaNum 14 }}
{{- $secretName := "neo4j-ztna-pass" }}

{{- $secret := list }}
{{- $secret = (lookup "v1" "Secret" .Release.Namespace "neo4j-ztna-pass") }}

{{- if $secret }}
  {{- $password = index $secret.data "NEO4J_AUTH" | b64dec | trimPrefix "neo4j/" -}}
{{- end -}}

{{- $passwd :=  printf "neo4j/%v" $password | b64enc -}}

apiVersion: v1
kind: Secret
metadata:
  name: "neo4j-ztna-pass"
  namespace: "default"
  labels:
    app: "neo4j-ztna"
type: Opaque
data:
  NEO4J_AUTH: "{{ $passwd }}"
{{ end }}
