apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: block
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi 
